# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from lpesmfold_light_microservice.models.http_validation_error import HTTPValidationError
from lpesmfold_light_microservice.models.is_job_running_response import IsJobRunningResponse
from lpesmfold_light_microservice.models.run_esm_fold_prediction_request import RunEsmFoldPredictionRequest
from lpesmfold_light_microservice.models.run_esm_fold_prediction_response import RunEsmFoldPredictionResponse
from lpesmfold_light_microservice.models.validation_error import ValidationError
from lpesmfold_light_microservice.models.validation_error_loc_inner import ValidationErrorLocInner
